from django.db import models

class Section(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=100)
    keywords = models.TextField()
    form = models.PositiveSmallIntegerField()
    ovz = models.TextField()
    mun_id = models.PositiveSmallIntegerField()
    operator_id = models.PositiveIntegerField()
    organization_id = models.PositiveIntegerField()
    hours = models.PositiveIntegerField()
    location_lat = models.TextField()
    location_lon = models.TextField()
    age_min = models.PositiveSmallIntegerField()
    age_max = models.PositiveSmallIntegerField()
    years = models.PositiveIntegerField()
    direction_id = models.PositiveIntegerField()
    direction_name = models.TextField()
    image = models.TextField()
    organization_name = models.TextField()
    address = models.TextField()
    certified = models.BooleanField()
    commercial = models.BooleanField()
    meaningful = models.BooleanField()
    general = models.BooleanField()
    preprofessional = models.BooleanField()